# Generated by Django 4.2.7 on 2026-05-01 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('brouillon', 'Brouillon'), ('envoyee', 'Envoyée'), ('confirmee', 'Confirmée'), ('recue_partielle', 'Reçue partiellement'), ('recue', 'Reçue totalement'), ('cloturee', 'Clôturée'), ('annulee', 'Annulée')], default='brouillon', max_length=20)),
                ('expected_date', models.DateField(blank=True, null=True, verbose_name='Livraison prévue')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_ordered', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity_received', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Ligne de commande',
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=30, unique=True)),
                ('title', models.CharField(max_length=200, verbose_name='Objet')),
                ('status', models.CharField(choices=[('brouillon', 'Brouillon'), ('soumis', 'Soumis'), ('en_validation', 'En validation'), ('valide', 'Validé'), ('rejete', 'Rejeté'), ('commande', 'Commandé')], default='brouillon', max_length=20)),
                ('priority', models.CharField(choices=[('normale', 'Normale'), ('urgente', 'Urgente'), ('critique', 'Critique')], default='normale', max_length=10)),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Département')),
                ('needed_date', models.DateField(blank=True, null=True, verbose_name='Date souhaitée')),
                ('notes', models.TextField(blank=True, verbose_name='Remarques')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': "Demande d'achat",
                'verbose_name_plural': "Demandes d'achat",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequestLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Quantité')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix unitaire estimé')),
                ('notes', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Ligne de demande',
            },
        ),
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=50, verbose_name='BL Fournisseur')),
                ('notes', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Réception',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='ReceptionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_received', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ValidationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('soumission', 'Soumission'), ('validation', 'Validation'), ('rejet', 'Rejet'), ('annulation', 'Annulation'), ('modification', 'Modification')], max_length=20)),
                ('comment', models.TextField(blank=True, verbose_name='Commentaire')),
                ('old_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log de validation',
                'ordering': ['-created_at'],
            },
        ),
    ]
