# Generated by Django 4.2.7 on 2026-05-01 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0001_initial'),
        ('products', '0001_initial'),
        ('purchases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='validationlog',
            name='performed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='validationlog',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='purchases.purchaserequest', verbose_name='Demande'),
        ),
        migrations.AddField(
            model_name='receptionline',
            name='order_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchases.purchaseorderline'),
        ),
        migrations.AddField(
            model_name='receptionline',
            name='reception',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchases.reception'),
        ),
        migrations.AddField(
            model_name='reception',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receptions', to='purchases.purchaseorder'),
        ),
        migrations.AddField(
            model_name='reception',
            name='received_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaserequestline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='Article'),
        ),
        migrations.AddField(
            model_name='purchaserequestline',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchases.purchaserequest', verbose_name='Demande'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requests', to=settings.AUTH_USER_MODEL, verbose_name='Demandé par'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_lines', to='purchases.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='ordered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='purchase_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order', to='purchases.purchaserequest'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suppliers.supplier', verbose_name='Fournisseur'),
        ),
    ]
