# Generated by Django 5.2.14 on 2026-05-23 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_auditlog_notification_supplierconsultation_and_more'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierRequestConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('critique', 'Stock critique'), ('rupture', 'Rupture de stock'), ('indisponible', 'Article indisponible')], max_length=20)),
                ('status', models.CharField(choices=[('ouverte', 'Ouverte'), ('en_cours', 'En cours'), ('cloturee', 'Cloturee')], default='ouverte', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='Objet')),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_conversations', to=settings.AUTH_USER_MODEL, verbose_name='Demandeur')),
                ('purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_conversations', to='purchases.purchaserequest', verbose_name='Demande')),
                ('request_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_conversations', to='purchases.purchaserequestline', verbose_name='Ligne de demande')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_conversations', to='suppliers.supplier', verbose_name='Fournisseur')),
            ],
            options={
                'verbose_name': 'Conversation fournisseur',
                'verbose_name_plural': 'Conversations fournisseurs',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierRequestMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('demandeur', 'Demandeur'), ('fournisseur', 'Fournisseur')], max_length=20)),
                ('body', models.TextField(verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='purchases.supplierrequestconversation')),
                ('sender_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sent_messages', to='suppliers.supplier')),
                ('sender_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message fournisseur',
                'verbose_name_plural': 'Messages fournisseurs',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='supplierrequestconversation',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['ouverte', 'en_cours'])), fields=('request_line', 'supplier'), name='unique_open_supplier_conversation_per_line'),
        ),
    ]
