# Generated by Django 5.2.14 on 2026-05-23 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('purchases', '0004_supplierrequestconversation_supplierrequestmessage_and_more'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='suppliers.supplier', verbose_name='Fournisseur'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='products.product'),
        ),
        migrations.AlterField(
            model_name='purchaserequestline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_lines', to='products.product', verbose_name='Article'),
        ),
        migrations.AlterField(
            model_name='reception',
            name='received_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='receptionline',
            name='order_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reception_lines', to='purchases.purchaseorderline'),
        ),
        migrations.AlterField(
            model_name='supplierrequestconversation',
            name='trigger',
            field=models.CharField(blank=True, choices=[('critique', 'Stock critique'), ('rupture', 'Rupture de stock'), ('indisponible', 'Article indisponible')], max_length=20),
        ),
        migrations.AlterField(
            model_name='validationlog',
            name='performed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='validation_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
