# Generated by Django 5.2.14 on 2026-06-02 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0005_alter_auditlog_user_alter_purchaseorder_supplier_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reception',
            options={'ordering': ['-received_at'], 'verbose_name': 'RÃ©ception'},
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier_delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date livraison proposee'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier_document_reference',
            field=models.CharField(blank=True, max_length=120, verbose_name='Reference devis/facture/BL'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier_note',
            field=models.TextField(blank=True, verbose_name='Note fournisseur'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier_quote_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Montant devis fournisseur'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier_responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier_response_status',
            field=models.CharField(choices=[('en_attente', 'En attente fournisseur'), ('devis_envoye', 'Devis envoye'), ('confirmee', 'Confirmee par fournisseur'), ('refusee', 'Refusee par fournisseur'), ('preparation', 'En preparation'), ('expediee', 'Expediee'), ('livree', 'Livree')], default='en_attente', max_length=20, verbose_name='Statut fournisseur'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='expected_date',
            field=models.DateField(blank=True, null=True, verbose_name='Livraison prÃ©vue'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('envoyee', 'EnvoyÃ©e'), ('confirmee', 'ConfirmÃ©e'), ('expediee', 'Expediee'), ('recue_partielle', 'ReÃ§ue partiellement'), ('recue', 'ReÃ§ue totalement'), ('cloturee', 'ClÃ´turÃ©e'), ('annulee', 'AnnulÃ©e')], default='brouillon', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='department',
            field=models.CharField(blank=True, max_length=100, verbose_name='DÃ©partement'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='needed_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date souhaitÃ©e'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requests', to=settings.AUTH_USER_MODEL, verbose_name='DemandÃ© par'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('soumis', 'Soumis'), ('en_validation', 'En validation'), ('valide', 'ValidÃ©'), ('rejete', 'RejetÃ©'), ('commande', 'CommandÃ©')], default='brouillon', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaserequestline',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='QuantitÃ©'),
        ),
        migrations.AlterField(
            model_name='purchaserequestline',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix unitaire estimÃ©'),
        ),
    ]
