# Generated by Django 5.2.14 on 2026-06-18 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0006_alter_reception_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierrequestconversation',
            name='trigger',
            field=models.CharField(blank=True, choices=[('demande', 'Demande fournisseur'), ('critique', 'Stock critique'), ('rupture', 'Rupture de stock'), ('indisponible', 'Article indisponible')], max_length=20),
        ),
    ]
