# Generated by Django 4.2.7 on 2026-05-01 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie'), ('ajustement', 'Ajustement'), ('transfert', 'Transfert'), ('retour', 'Retour')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Quantité')),
                ('stock_before', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Stock avant')),
                ('stock_after', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Stock après')),
                ('reference', models.CharField(blank=True, max_length=50, verbose_name='Référence')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='Motif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-created_at'],
            },
        ),
    ]
