# Generated by Django 4.2.7 on 2026-05-01 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Référence')),
                ('name', models.CharField(max_length=200, verbose_name='Désignation')),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(choices=[('pièce', 'Pièce'), ('kg', 'Kilogramme'), ('litre', 'Litre'), ('carton', 'Carton'), ('palette', 'Palette'), ('mètre', 'Mètre'), ('lot', 'Lot')], default='pièce', max_length=20, verbose_name='Unité')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix unitaire')),
                ('current_stock', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Stock actuel')),
                ('min_stock', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Seuil minimum')),
                ('max_stock', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Stock maximum')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category', verbose_name='Catégorie')),
                ('suppliers', models.ManyToManyField(blank=True, related_name='products', to='suppliers.supplier', verbose_name='Fournisseurs')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['name'],
            },
        ),
    ]
