# Generated by Django 5.2.14 on 2026-05-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('demandeur', 'Demandeur'), ('validateur', 'Validateur'), ('acheteur', 'Acheteur'), ('magasinier', 'Magasinier'), ('direction', 'Direction')], default='demandeur', max_length=20),
        ),
    ]
