# Generated by Django 5.2.14 on 2026-05-23 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='suppliers.supplier', verbose_name='Fournisseur lie'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('demandeur', 'Demandeur'), ('validateur', 'Validateur'), ('acheteur', 'Acheteur'), ('magasinier', 'Magasinier'), ('direction', 'Direction'), ('fournisseur', 'Fournisseur')], default='demandeur', max_length=20),
        ),
    ]
